# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a51b7676ec5596cbedb7b8046604bba2ae1ff3cb8adc4d09a2b905e7e74876e61191096cd70dc499237254f82d3a1df19780a48fa926c52c8d801287c47b673d

test:
  secret_key_base: a249d6dd92853aba8c7553a11aa3b75119b581c8901eab3dc134dc92beead8de94477316c339bbf6a59070a9afe6604f4141a9ce2ad0de654b51043d028dd8ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
